name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_TYPE: stable

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
        run: |
          RELEASE_TYPE="${{ github.event.inputs.release_type || 'main' }}"
          if [[ "$RELEASE_TYPE" == "alpha" ]]; then
            semantic-release version --prerelease alpha
          elif [[ "$RELEASE_TYPE" == "beta" ]]; then
            semantic-release version --prerelease beta
          else
            semantic-release version
          fi